
IMPORT INTO  "EMPLOYEES" 
   ( "EMPLOYEE_ID","FIRST_NAME","LAST_NAME","EMAIL","PHONE_NUMBER","HIRE_DATE","JOB_ID","SALARY","COMMISSION_PCT","MANAGER_ID","DEPARTMENT_ID")
   CSV DATA ("nodelocal://1/employees.csv") WITH skip='1', nullif = '';